### PR TITLE
Fixed typos

### PR DESCRIPTION
**Pull request by dimitris-t**
Fixed various typos in multiple documents.

### CODE REVIEW

**Comment by rustyrussell** [comment]
OK, so massive copywriting happening at the moment; I'll apply this once that's settled down if they're not already all fixed.  Thanks!

**Comment by shannona** [comment]
I added the fix for BOLT-8 to #311. No one has BOLT-11 right now, so either that one bit can be incorporated, or we can leave this open until I get to BOLT-11, hopefully next week.

**Comment by shannona** [comment]
I'm now working on BOLT-11 and have verified that this change is in; that should be all the referenced BOLTs, so this can be closed.

**Comment by shannona** [comment]
I believe these have now been all accounted for, and this PR can be closed.

**Comment by dimitris-t** [comment]
Closing this PR as its changes went into other commits.

**Pull request closed without merging**
