### PR TITLE
BOLT 3: fix transaction test vectors 

### PR DESCRIPTION
**Pull request by sstone**
- rename keys properly (see #90)
- fix fees
- fix remote-output (it's a P2PKH output, we incorrectly used a P2WPH output)
- sign all transactions

### CODE REVIEW

**Comment by rustyrussell** [comment]
OK, this still leaves me very confused.  This needs many more comments in the test vectors, IMHO: lines starting with # which help implementers debug where they went wrong.  As my teacher used to say "show your working!".

What commitment tx number are we producing?  0? How do we produce the obscured commitment transaction number?  That needs the payment-basepoint for both sides for the obscuring factor.  It seems you've used commitment number 42, and the local_payment_key and remote_payment_key as the basepoints?  Thats wrong...

For HTLC outputs and the to-local output, we need the delayed-localkey, and we don't have it, either.

I'm reworking this now...

**Comment by sstone** [comment]
Our intent was to generate basic tx test vectors that can be used to check scripts, ordering, ... and make sure that all implementation agree on a basic level, because we believe that it makes building implementations incrementally easier. This is why we did not include key derivation (which makes generation and verification of test vectors more involved). They are meant as: "if keys look like this, then txs should look like this".
 
But you're right: the transaction number does use payment basepoints, we cannot just pick random keys, instead we need to derive them from the same basepoints. So there is really a problem here, which I missed when I added the commit tx number obfuscation and updated our test vectors :(

I've fixed the txs (the to-remote ouput has changed anyway), added comments and updated the PR

sidenote: Regarding the `delayed-localkey`, in our implementation we used it everywhere in the local tx, both for the delayed payment outputs (main+htlc) and in the multisig htlc outputs. This is not what the spec says (mea maxima culpa!) and I just realized it. OTOH, the way the spec is currently written, the same `localkey` will be used in two otherwise unrelated transactions (with the same tx index): a local tx (for the multisig htlc output) and a remote tx (for direct to-us payments). Is that really a good thing?

**Comment by rustyrussell** [comment]
> This is not what the spec says (mea maxima culpa!) and I just realized it. OTOH, the way the spec is currently written, the same localkey will be used in two otherwise unrelated transactions (with the same tx index): a local tx (for the multisig htlc output) and a remote tx (for direct to-us payments). Is that really a good thing?

Yes, I considered adding another key, but it doesn't help at all.  You can tell from the forms of the script which party is being paid for both cases anyway.

**Comment by rustyrussell** [comment]
After discussion, this was closed in favor of #99 which Fabrice already debugged for me :)

**Pull request closed without merging**
