### PR TITLE
bolt-09: reserve feature bits for option_anchors_zero_fee_htlc_tx

### PR DESCRIPTION
**Pull request by halseth**
See #824. This PR only reserves the feature bits.

### CODE REVIEW

**Review by t-bast — COMMENTED** [review]
ACK, just needs some fixing for the CI (I think `txs` and `vuln` can be added to the dictionary)

**Comment by halseth** [comment]
did some renaming, still had to add `sighash` to the dictionary.

**Review by t-bast — APPROVED** [review]
ACK https://github.com/lightningnetwork/lightning-rfc/pull/828/commits/c4f940721c7a541c908cbdc063437ffe65417eaf

**Comment by cdecker** [comment]
ACK c4f940721c7a541c908cbdc063437ffe65417eaf

**Pull request merged**
