### PR TITLE
Add CC-BY.

### PR DESCRIPTION
**Pull request by rustyrussell**
Please explicitly acknowledge!  @cdecker @Roasbeef @sstone @pm47 @josephpoon @adiabat @BitfuryLightning 

Closes: #2

### CODE REVIEW

**Comment by adiabat** [comment]
ACK; CC-BY is fine with me.

**Comment by cdecker** [comment]
LGTM :+1:

**Comment by pm47** [comment]
ACK

**Comment by Roasbeef** [comment]
I'm fine with CC-BY.

**Comment by sstone** [comment]
ACK

**Comment by BitfuryLightning** [comment]
ACK

**Comment by cdecker** [comment]
Merging, since 7 out of 8 contributors have ACKd this :-)

**Pull request merged**
