### PR TITLE
BOLT2: both nodes send `update_add_htlc`

### PR DESCRIPTION
**Pull request by nayuta-ueno**
issue #472

In this sequence, three `commitment_signed` and `revoke_and_ack` are required.

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
This should not be the case. When B sends A a commitment_signed it should absolutely include any pending update_adds *from* B.

**Comment by nayuta-ueno** [comment]
@TheBlueMatt 
> When B sends A a commitment_signed it should absolutely include any pending update_adds from B.
When `B` receive `revoke_and_ack`(7), `B` have signed commitment transaction HTLC1, 2 (HTLC3 has only applied).
Therefore 'A' need sends `commitment_singed`(8).

**Comment by nayuta-ueno** [comment]
@pm47 Thank you for your review!
(I'm not `@ ueno` but @nayuta-ueno :)

**Comment by rustyrussell** [comment]
You are correct, the example was unclear.  Perhaps deliberately so, as below it says:

```
what matters is whether both sides have irrevocably committed to a
particular HTLC or not (the final state, above).
```

Which implies that it's deliberate that one side is committed to the HTLC and the other isn't?  We should probably spell out the states at each point for each side, but that's a separate commit.

**Pull request merged**
