### PR TITLE
BOLT5: Unify two practically redundant paragraphs

### PR DESCRIPTION
**Pull request by jtimon**
The two paragraph seem quite redundant and repetitive. Perhaps the resulting one can even be simplified even further.

### CODE REVIEW

**Comment by cdecker** [comment]
ACK 4f35fd391b275af45b01f3c2567e003f1931bdce

**Comment by jtimon** [comment]
As discussed on IRC, the second paragraph seems just a more specific version of the first one. So I could simply remove the first paragraph and leave the second one as is. Or I could just leave it at what I have now, or follow some other suggestion too.

**Comment by jtimon** [comment]
Please, chose between commit 1 alone or both squashed. I think we all agree both options are improvements, I don't care either way.

**Comment by cdecker** [comment]
Merging like discussed during the [last specification meeting](http://www.erisian.com.au/meetbot/lightning-dev/2019/lightning-dev.2019-05-13-20.03.html)

**Comment by jtimon** [comment]
I could have squashed, but I guess it doesn't really matter.

**Pull request merged**
