### PR TITLE
Correct hint for P2WPKH

### PR DESCRIPTION
**Pull request by benthecarman**

### CODE REVIEW

**Review by t-bast — APPROVED** [review]

**Comment by TheBlueMatt** [comment]
ACK but note conflicts with https://github.com/lightningnetwork/lightning-rfc/pull/672 so maybe @rustyrussell wants to just take it via that PR.

**Comment by benthecarman** [comment]
> ACK but note conflicts with #672 so maybe @rustyrussell wants to just take it via that PR.

It shouldn't conflict, his pr does not touch line 494

**Comment by TheBlueMatt** [comment]
Hum, I had thought git would call it a conflict if there’s a change within 2 lines, but I admit I think I just always assumed that.

**Comment by rustyrussell** [comment]
Applying under the Spelling Rule.

**Pull request merged**
