### PR TITLE
BOLT 3: fix witness scripts

### PR DESCRIPTION
**Pull request by sstone**
Add a short paragraph on P2WSH (the witness script is omitted for brevity in all descriptions) and fix witness scripts for spending the different tx outputs.

### CODE REVIEW

**Comment by Roasbeef** [comment]
What's the rationale behind moving from CMSV to CMS? Unintended clean-stack interaction perhaps?

**Comment by rustyrussell** [comment]
Thanks for the review!

Tadge caught my VERIFY error before and I didn't fix these.  And the witnesses were from an older variant.  As you can tell, they're still untested...

**Comment by rustyrussell** [comment]
@sstone Hmm, want to review my math on fee calculation as well?  See #22 

Similarly, the Penalty Transaction Weight Calculation in BOLT 5.

**Comment by rustyrussell** [comment]
Squashed and merged, with slightly more detailed commit msg.  Thanks!

**Comment by sstone** [comment]
@Roasbeef yes, you need a final stack with a single "1" and since CMSV cleans the stack this "1" had to be added to the witness script of the spending tx, it is cleaner with CMS

@rustyrussell I'm reviewing the fee calculation and will create a PR if needed

**Pull request closed without merging**
