### PR TITLE
BOLT 2: specify requirement not to send fulfill until both sides locked in

### PR DESCRIPTION
**Pull request by rustyrussell**
Otherwise you can lose funds!

### CODE REVIEW

**Comment by pm47** [comment]
ACK, we actually have a bug related to this in eclair!

**Comment by cdecker** [comment]
ACK 34e92aa2af9c8bcdc32d107d3f9dd332c37d5428

**Comment by pm47** [comment]
Thinking more about this, should we add a warning about the risk of forwarding an htlc if the sender isn't locked in? In an A->B->C setup, an adversarial counterparty A could make the forwarding node B lock his funds in the B-C channel without having anything at stake in the A-B channel. There is no risk of loss of funds, but that could make some of B's funds temporarily unusable.

**Comment by pm47** [comment]
Answering to myself: B can mitigate the risk using `max-accepted-htlcs` and `max-htlc-value-in-flight-msat`.

**Comment by pm47** [comment]
I think B actually does risk losing funds by forwarding an htlc that is not signed by both sides. Consider this scenario:
```
A            B            C
|    add     |            |
|----------->|            |
|    sig     |            |
|----------->|            |
|    rev     |            |
|< ----------|            |
|            |    add     |
|            |----------->|
|            |    sig     |
|            |----------->|
|            |    rev     |
|            |<-----------|
|            |    sig     |
|            |<-----------|
|            |    rev     |
|            |----------->|
|            |            | C forwards the htlc
|            |            | and eventually gets
|            |            | the payment preimage
|            |            |
```

At this point if A publishes its commitment transaction and gets it confirmed, B will lose funds no matter what happens between B and C.

Am I overthinking this?

**Comment by rustyrussell** [comment]
Pierre-Marie Padiou <notifications@github.com> writes:
> Thinking more about this, should we add a warning about the risk of forwarding an htlc if the sender isn't locked in? In an A->B->C setup, an adversarial counterparty A could make the forwarding node B lock his funds in the B-C channel without having anything at stake in the A-B channel. There is no risk of loss of funds, but that could make some of B's funds temporarily unusable.

It *does* lead to loss of funds.  C gives preimage, A drops commitment
transaction without HTLC to chain.  Oops.

(Oh, you noted this later).

Yes, this is where the extra latency comes from: B needs A to be locked
in ("irrevocably committed") to the HTLC before it can commit to C.  And
the way that HTLCs work, this means B will be committed to the HTLC with
A too.

The only case where you can act before this commitment is in the case of
fulfilling an HTLC, as knowledge of the preimage can't be revoked :)

Cheers,
Rusty.

**Comment by pm47** [comment]
>It *does* lead to loss of funds. C gives preimage, A drops commitment transaction without HTLC to chain. Oops.

Even if C doesn't give B the preimage, if C just publishes its commitment transaction he will pull funds from B, and even if B is able to retrieve the preimage from the blockchain, it won't be able to use it if A publishes its commitment tx.

>The only case where you can act before this commitment is in the case of fulfilling an HTLC, as knowledge of the preimage can't be revoked :) 

But it is too late already at this point I think. In my example B does not yet have the preimage and is already in danger of loosing funds. Shouldn't the spec also say something like this: "An htlc should not be "cross-committed" on the right side of a node if it isn't on the left side of a node"? And if we add this to the spec, then it *implies* the change made in this PR right? (and if you are the last node in the route the hltc needs to be cross-committed before you give the coffee to the customer)

Cheers,

Pierre

**Comment by rustyrussell** [comment]
Pierre-Marie Padiou <notifications@github.com> writes:
>>It *does* lead to loss of funds. C gives preimage, A drops commitment transaction without HTLC to chain. Oops.
>
> Even if C doesn't give B the preimage, if C just publishes its commitment transaction he will pull funds from B, and even if B is able to retrieve the preimage from the blockchain, it won't be able to use it if A publishes its commitment tx.

Yes.

>
>>The only case where you can act before this commitment is in the case of fulfilling an HTLC, as knowledge of the preimage can't be revoked :) 
>
> But it is too late already at this point I think. In my example B does
> not yet have the preimage and is already in danger of loosing
> funds.

Sorry, I was being unclear, and stating an exception to the general
rule.

> Shouldn't the spec also say something like this: "An htlc
> should not be "cross-committed" on the right side of a node if it
> isn't on the left side of a node"? And if we add this to the spec,
> then it *implies* the change made in this PR right? (and if you are
> the last node in the route the hltc needs to be cross-committed before
> you give the coffee to the customer)

Yes, we probably need a section on forwarding.  Is this clearer?

Insert this before "Risks With HTLC Timeouts" and rework the first
paragraph of that to match this:

### Forwarding HTLCs

In general, a node offers HTLCs for two reasons: to initiate a payment
of its own, or to forward a payment coming from another node.  In the
forwarding case, care must be taken to ensure that the *outgoing* HTLC
cannot be redeemed unless the *incoming* HTLC can be redeemed; these
requirements ensure that is always true.

The addition/removal of an HTLC is considered *irrevocably committed*
when:

1. the commitment transaction with/without it it is committed by both
   nodes, and any previous commitment transaction which without/with it
   has been revoked, OR
2. the commitment transaction with/without it has been irreversibly
   committed to the blockchain.

#### Requirements

A node MUST NOT offer an HTLC (`update_htlc_add`) in response to an
incoming HTLC until the incoming HTLC has been irrevocably committed.

A node MUST NOT fail an incoming HTLC (`update_fail_htlc`) for which it
has committed to an outgoing HTLC, until the removal of the outgoing
HTLC is irrevocably committed.

A node SHOULD fulfill an incoming HTLC for which it has committed to an
outgoing HTLC, as soon as it receives `update_fulfill_htlc` for the
outgoing HTLC.

#### Rationale

In general, we need to complete one side of the exchange before dealing
with the other.  Fulfilling an HTLC is different: knowledge of the
preimage is by definition irrevocable, so we should fulfill the incoming
HTLC as soon as we can to reduce latency.

**Pull request merged**
