### PR TITLE
BOLT 7,8,11: Add table-of-contents

### PR DESCRIPTION
**Pull request by bcongdon**
Adds table-of-contents to BOLT's 7, 8, and 11.

### CODE REVIEW

**Comment by shannona** [comment]
I will incorporate the ToCs for #7 and #8 into the PRs I have open on them right now.

**Comment by rustyrussell** [comment]
Great!  @shannona, make sure you credit @bcongdon ; it's easy to lose attribution when patches are flying around like this!

**Comment by shannona** [comment]
Absolutely. I was going to be sure to flag him in the pull. Let me know if anything else is appropriate for Github.

**Comment by shannona** [comment]
Table of contents for BOLT-7 and BOLT-8 are now incorporated into #307 and #311, respectively. If the BOLT-11 ToC hasn't been incorporated by the time I get there, I'll make sure it's in place.

**Comment by bcongdon** [comment]
Sounds good. Thanks!

**Pull request closed without merging**
